trustPolicy: no-downgrade
shellEmulator: true
minimumReleaseAge: 1440
minimumReleaseAgeExcludePrune: true

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - why-is-node-running@3.2.2
  - '@netlify/serverless-functions-api@2.23.0'
  - '@netlify/serverless-functions-api@2.18.0'

packages:
  - .

catalog:
  '@antfu/eslint-config': 9.5.1
  '@astrojs/check': 0.9.10
  '@astrojs/vue': 7.0.3
  '@playwright/test': 1.63.0
  '@portabletext/to-html': 6.0.0
  '@portabletext/types': 4.0.2
  '@sanity/client': 8.9.0
  '@sanity/image-url': 2.1.1
  '@testing-library/dom': 10.4.2
  '@testing-library/jest-dom': 7.0.1
  '@testing-library/user-event': 14.6.7
  '@vitest/coverage-v8': 5.0.3
  astro: 7.3.5
  eslint: 10.11.0
  eslint-plugin-astro: 3.2.1
  eslint-plugin-playwright: 2.12.0
  eslint-plugin-testing-library: 7.16.2
  groq: 6.16.0
  happy-dom: 20.14.5
  lighthouse: 13.5.0
  msw: 3.0.1
  netlify-cli: 27.10.1
  playwright: 1.63.0
  typescript: 5.9.3
  vitest: 5.0.3
  vue: 3.5.43

allowBuilds:
  esbuild: true
  msw: true
  netlify-cli: true
  sharp: true
  unix-dgram: true

minimumReleaseAgeExclude:
  - '@netlify/edge-bundler@16.1.1'
  - netlify-cli@27.10.1
